### ISSUE TITLE
锁定帖子功能

### ISSUE THREAD

**Issue by hasbai** [OpenTreeHole/treehole_next#12]
**Describe the feature**

[//]: # (A clear and concise description of what the feature is.)

锁定 hole，禁止非管理员发帖和修改 tag

**Describe how to implement it**

[//]: # (if possible)

**What does this feature intend to do**

[//]: # (To solve a waht problem, or to meet a what demand)

有的时候帖子讨论的内容偏离主题了，就不适宜在这个帖子下继续讨论下去了

**Additional context**

[//]: # (Add any other context about the feature request here.)

**Comment by JingYiJun** [comment]
finished in https://github.com/OpenTreeHole/treehole_next/commit/cf57e6e0262bbd3884e25c57ecc914068c5d75a3
