### ISSUE TITLE
管理操作记录

### ISSUE THREAD

**Issue by fsy2001** [OpenTreeHole/treehole_next#62]
**Describe the feature**

将所有管理操作记录在数据库。管理操作包括：删帖、禁言、编辑他人帖子。

**Describe how to implement it**

建立一个单独的数据库，按管理操作分成若干个表，记录相关属性。

无需实现查询API，直接给管理团队提供读取数据库的权限。

实体类的初步设计：

```go
// 删贴
type AdminDeleteAction struct {
  FloorID  int
  Reason   string
  Content  string
  Operator int
}

// 禁言
type AdminBanAction struct {
  FloorID   int
  Content   int
  Operator  int
  Duration  int
}

// 编辑他人帖子
type AdminEditAction struct {
  FloorID     int
  Content     string
  EditContent string
  Operator    int
}
```

**What does this feature intend to do**

供管理团队内部审计使用。

**Additional context**

[//]: # (Add any other context about the feature request here.)

**Comment by JingYiJun** [comment]
打算搭一套ELK
