### ISSUE TITLE
禁言功能迁移

### ISSUE THREAD

**Issue by fsy2001** [OpenTreeHole/treehole_next#63]
**Describe the feature**

树洞内的禁言功能应在treehole微服务内实现，并提供查询禁言状态的接口。

**Describe how to implement it**

建立 `ban` 数据表，其中包含 `user_id, expire_date, ban_division` 三列。禁言时根据是否仍在禁言选择叠加或更新 `expire_date`。用户发言时查询其 `expire_date` 是否已到期判断是否允许其发言。

提供接口供用户查询其在各板块中的禁言状态。

提供接口供管理员提前解除禁言。

**What does this feature intend to do**

降低treehole微服务与auth和网关的耦合。

**Additional context**

[//]: # (Add any other context about the feature request here.)

**Comment by fsy2001** [comment]
管理员提前解除禁言是否有必要做成接口？能不能直接用SQL解决

**Comment by JingYiJun** [comment]
已经实现相关功能，提前接触禁言使用SQL解决
