### ISSUE TITLE
POST /floors/{id}/like/{like} 返回的 floor 实例不正确

### ISSUE THREAD

**Issue by dest1n1s** [OpenTreeHole/treehole_next#65]
**Describe the bug**

POST /floors/{id}/like/{like} 返回的 floor 实例中始终带有空的 `mention` 数组。

**Expected behavior (Optional)**

应带有正确的 `mention` 数组。

**Comment by JingYiJun** [comment]
已修复，待验证测试 [c005086fdf9ced9871f8cfabe165d6a451723ac0](https://github.com/OpenTreeHole/treehole_next/commit/c005086fdf9ced9871f8cfabe165d6a451723ac0)
