### ISSUE TITLE
站内信

### ISSUE THREAD

**Issue by QLTyrone** [OpenTreeHole/treehole_next#76]
**此Issue搬运自飞书原《功能需求和bug修复建议》文档**

**备注**
起初是为了在不开盒的前提下，允许我们与某用户单独交流（如用户疑似出现生命威胁，如学校希望与某同学交流但同意采用间接交流的方式）。该功能可在一定程度上减少开盒次数、提高沟通效率。
按照目前的需求看，允许站方通过不要太复杂的操作即可给同学发通知即可。
后续可能会和“建议修改”功能结合，即利用修改功能将原文全文改为建议修改，并且同时将原文和建议修改原因推送给该用户便于修改。以尽可能避免破坏同学原意。（不过关于是否要引入、如何引入建议修改机制，可能需要开会讨论）

**提出部门**
社区运营部

**Comment by JingYiJun** [comment]
finished [#64](https://github.com/OpenTreeHole/treehole_next/issues/64)
