### ISSUE TITLE
[Bug] 删除帖子后，应仅有管理员可修改帖子内容

### ISSUE THREAD

**Issue by w568w** [OpenTreeHole/treehole_next#77]
目前客户端在用户自行删除帖子后不会立刻刷新（或者由于网络原因未能及时刷新），用户依然可以长按帖子选择编辑，修改删除后的默认文本（即「该内容被作者删除」）。

这可能会导致错误的行为，例如用户自行删除帖子后，将帖子内容修改为「该内容因 xxx（二级封禁）删除」，从而引发他人错误的认知。

应当在后端禁止对于已删除帖子的、非管理员来源的编辑。

**Comment by JingYiJun** [comment]
completed in e92d20db557b848592120077cc68840e9f1c4b3b
