### ISSUE TITLE
账户注销与重新注册

### ISSUE THREAD

**Issue by KYLN24** [OpenTreeHole/treehole_next#88]
**Describe the feature**

[//]: # 账户注销后，将原有 user 表中的项标记为已删除，并将其 identifier 设为 null。新用户注册时，应当创建一个新的记录（即获得一个新的 user_id）

**Additional context**

[//]: # 账户注销时，应当检测是否还处于封禁期，以防通过注销重新注册的方式来解除禁言。

**Comment by JingYiJun** [comment]
finished in https://github.com/OpenTreeHole/auth_next/commit/edb499ec3e9184d587fb0545c27cd6fb917a7a17
