### ISSUE TITLE
管理员查询用户违规历史时，对于同一层的多次删除只返回一条删除记录

### ISSUE THREAD

**Issue by ppolariss** [OpenTreeHole/treehole_next#98]
**Describe the bug**

对同一层删除多次，查询违规历史时会得到多条重复的删除历史

**To Reproduce**

同一层多次删除后查询违规历史

**Expected behavior (Optional)**

对同一层多次删除后，只返回一条删除记录

**Additional context**

**Comment by JingYiJun** [comment]
46bcb9552e2e78d1d449a757e238e259141a5a28 已完成
